version: '3.7'

services:
    app:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        container_name: app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        working_dir: /var/www/html
        networks:
            - laravel
        depends_on:
            - mysql
    mysql:
        image: 'mysql/mysql-server:8.0'
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel
networks:
    laravel:
        driver: bridge
